global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pulse-monitoring'
    static_configs:
      - targets: ['app:9000']
        labels:
          app: gin-monitoring
